url: "https://grscicoll.hp.gbif-staging.org" # the base hostname & protocol for your staging site, e.g. https://hp-example.gbif-staging.org
testSite: true #style the site to show that it is a test site
webApi: "https://graphql.gbif-staging.org"

include: # this include is only to NOT exclude translations, so that they are visible in the staging
  - es/
  - it/
  - fr/
  - cs-CZ/
