url: "https://grscicoll.hp.gbif-staging.org" # the base hostname & protocol for your staging site, e.g. https://hp-example.gbif-staging.org
testSite: true #style the site to show that it is a test site