# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# You should also look at https://hp-theme.gbif-staging.org/documentation-intro for options
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GRSciColl # the title of your site should go here
email: info@gbif.org
description: >- # this means to ignore newlines (until baseurl:)
  An ever growing catalogue of the world’s natural history collections and the material they hold
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grscicoll.gbif.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gbif # if you have an account you want to link to. Else comment this line out
github_username:  gbif # if you have an account you want to link to. Else comment this line out

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: gbif/jekyll-hp-base-theme

# For use by the 'standardPrivacy' layout
privacy:
  name: GBIF
  domain: gbif.org
  contactEmail: info@gbif.org
  helpdeskEmail: info@gbif.org

# The text for the terms can be changed by adding translations for 'terms', 'acceptTerms' and 'rejectTerms' in `/_data/translations.yml`.
siteMeasurements:
  enable: false # When enabled there will be a popup asking the user for their consent. If they accept then the function "attachMeasurements" will be called. You can overwrite this function by adding a file `/_includes/js/measure.js` and replace the function.
  GA_ID: "G-XXXXXXXX" # Your Google analytics ID. Sometimes they start with UA-XXXXX-X other times with G-XXXXXXXX depending on how you set it up
  termsVersion: "2021-07-06" # A version number for your terms. If you change this, then the users will see the popup again asking them to confirm/reject anew.


algae:
  rootLang: en
  latestPostLimit: 3
  logo: /assets/images/logo.svg  # Logo in navbar, will be displayed with 28px height
  logoAndTitle: true             # include the title next to the logo
  archive_permalink: /news/       # Permalink of page using archive.html layout, required when using post categories
  style:
    square: true                  # Should corners be square or rounded
    colors:
      primary: "#a6906c"          # Primary color of your brand. Use HEX code. Used for buttons and links
      links: "#4c5f5f"            # What color should links have. Use a HEX code. DEfault is primary color. 
    coloredHeadlineLinks: false   # If a headline is a link, then use the link color. Default is true. 
  navbar:                         # RELATED TO NAVIGATION BAR
    brandBackground: "#62A8AC"    # Define a custom background for the logo/title in the top navigation bar
    color: "#37464c"              # What color should the navbar be?
    hasWhiteText: true            # Should the text color be white?

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .LICENSE
  - .netlify.toml
  - .README.md

permalink: pretty # will strip extensions like .html from urls

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page" # So by default any page will use the layout "page"
      lang: en # And have the default language english
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
